# Generated by Django 5.0.4 on 2024-05-18 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cargoes_qty', models.IntegerField()),
                ('cargoes_packed', models.IntegerField()),
                ('container_qty', models.IntegerField()),
                ('container_used', models.IntegerField()),
                ('fitness', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('length', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('length', models.IntegerField()),
                ('limit_weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X', models.IntegerField()),
                ('Y', models.IntegerField()),
                ('Z', models.IntegerField()),
                ('cargoes_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Loading.cargoes')),
                ('container_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Loading.container')),
            ],
        ),
        migrations.AddField(
            model_name='container',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Loading.project'),
        ),
        migrations.AddField(
            model_name='cargoes',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Loading.project'),
        ),
        migrations.AddField(
            model_name='cargoes',
            name='type_cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Loading.typecargo'),
        ),
        migrations.AddField(
            model_name='container',
            name='type_container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Loading.typecontainer'),
        ),
    ]
